name: CI/CD

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.11.1'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      env:
        PORT: ${{ secrets.PORT }}
        DB_CNN: ${{ secrets.DB_CNN }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        API_ENDPOINT_HEROKU: ${{ secrets.API_ENDPOINT_HEROKU }}
        NODE_ENV: ${{ secrets.NODE_ENV }}
        ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
        ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
      run: npm test

    - name: Deploy to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/gestion-horarios.git
        git push heroku main